services:
  - type: web
    name: rascatv3
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn stock_management.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: RENDER
        value: true
      - key: DEBUG
        value: false
    disk:
      name: data
      mountPath: /opt/render/project/data
      sizeGB: 1
