# Generated by Django 5.2.1 on 2025-05-19 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kode Barang')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Barang')),
                ('category', models.CharField(max_length=100, verbose_name='Kategori')),
                ('current_stock', models.IntegerField(default=0, verbose_name='Stok Saat Ini')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Jual')),
                ('minimum_stock', models.IntegerField(default=0, verbose_name='Stok Minimum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Aksi')),
                ('status', models.CharField(choices=[('success', 'Berhasil'), ('failed', 'Gagal')], default='success', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Nama File')),
                ('file_path', models.CharField(max_length=500, verbose_name='Path File')),
                ('file_size', models.IntegerField(default=0, verbose_name='Ukuran File (bytes)')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Upload')),
                ('success_count', models.IntegerField(default=0, verbose_name='Jumlah Item Berhasil')),
                ('error_count', models.IntegerField(default=0, verbose_name='Jumlah Item Gagal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Upload History',
                'verbose_name_plural': 'Upload Histories',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_webhook_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Webhook Telegram')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Setting',
                'verbose_name_plural': 'Webhook Settings',
            },
        ),
    ]
