# Generated by Django 5.2.1 on 2025-05-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_uploadhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooksettings',
            name='webhook_kelola_stok',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Webhook Telegram - Kelola Stok'),
        ),
        migrations.AddField(
            model_name='webhooksettings',
            name='webhook_transfer_stok',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Webhook Telegram - Transfer Stok'),
        ),
    ]
