# Generated by Django 5.2.1 on 2025-05-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Expired'),
        ),
    ]
