# Generated by Django 5.2.1 on 2025-05-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooksettings',
            name='webhook_data_exp_produk',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Webhook Telegram - Data Exp Produk'),
        ),
    ]
