# Generated by Django 5.2.1 on 2025-05-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_webhooksettings_webhook_data_exp_produk'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooksettings',
            name='webhook_kelola_harga',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Webhook Telegram - Kelola Harga'),
        ),
    ]
