# Generated by Django 5.2.1 on 2025-05-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_webhooksettings_webhook_kelola_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='latest_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Harga Terbaru'),
        ),
    ]
