# Generated by Django 5.2.1 on 2025-05-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_packingitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='transfer_stock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Stok Transfer'),
        ),
    ]
