# Generated by Django 5.2.1 on 2025-05-23 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_systemsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, verbose_name='Nomor Pesanan')),
                ('order_date', models.DateField(verbose_name='Tanggal Pemesanan')),
                ('cancellation_date', models.DateField(verbose_name='Tanggal Pembatalan')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Produk')),
                ('quantity', models.PositiveIntegerField(verbose_name='Jumlah')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='Alasan Pembatalan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User Input')),
            ],
            options={
                'verbose_name': 'Pesanan Dibatalkan',
                'verbose_name_plural': 'Pesanan Dibatalkan',
                'ordering': ['-cancellation_date', '-created_at'],
            },
        ),
    ]
