# Generated by Django 5.2.1 on 2025-05-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_cancelledorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='packingitem',
            options={'ordering': ['name'], 'verbose_name': 'Packing Item', 'verbose_name_plural': 'Packing Items'},
        ),
        migrations.AddField(
            model_name='webhooksettings',
            name='webhook_pesanan_dibatalkan',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Webhook Telegram - Pesanan Dibatalkan'),
        ),
    ]
