# Generated by Django 5.2.1 on 2025-05-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_cancelledorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooksettings',
            name='webhook_pesanan_dibatalkan',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Webhook Telegram - Pesanan Dibatalkan'),
        ),
    ]
